version: "3.9"
services:
  web0:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - ./web0:/code
    environment:
      FLASK_ENV: development
  web1:
    build: .
    ports:
      - "8001:5000"
    volumes:
      - ./web1:/code
  web2:
    build: .
    ports:
      - "8002:5000"
    volumes:
      - ./web2:/code
    environment:
      FLASK_ENV: development
  web3:
    build: .
    ports:
      - "8003:5000"
    volumes:
      - ./web3:/code
  web4:
    build: .
    ports:
      - "8004:5000"
    volumes:
      - ./web4:/code
